# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.6.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.6.4/lazyjira_darwin_amd64.tar.gz"
      sha256 "eb2b625d275d9387c4637e61d04df6a066d46ce9e83480e7dd38d3890c7d28c8"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.6.4/lazyjira_darwin_arm64.tar.gz"
      sha256 "fd22fcaf22fd573bdffabd0e83a3ac5ee3b379148d90dbcf8b0496e1cc2c79c1"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.6.4/lazyjira_linux_amd64.tar.gz"
      sha256 "9cea3a88af9c5507834faa77e789473d5e35eb3fe466ad07f27dc07bd6ac0931"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.6.4/lazyjira_linux_arm64.tar.gz"
      sha256 "e23fe9787c9f7a8b5a0bc61ca23c6a6487e3c6658a1796e8dca86d230ff56abe"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end
end
