# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.10.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.10.1/lazyjira_darwin_amd64.tar.gz"
      sha256 "5cd961161a4655b40dd51ce7b9838a2d7faee26621ad539e51dca5e9f929cd3e"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.10.1/lazyjira_darwin_arm64.tar.gz"
      sha256 "57bcca947e14f47e0c7b89dcb87aa9a8e000c323f5211a1c68fde31f97454a9d"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.10.1/lazyjira_linux_amd64.tar.gz"
      sha256 "da8b953e7999d64a19d269d04b21e97cee6347d22ca4a8c1658927dbc17d9482"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.10.1/lazyjira_linux_arm64.tar.gz"
      sha256 "4db698a213ba4180f111588a44480f4e06302faab56b471c7aa01c46ce0f4300"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end
end
