# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyjira" do
  name "lazyjira"
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyjira"

  on_macos do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_amd64.tar.gz"
      sha256 "7d27b31167495cd641756c096efdd612ff342633d548f5550008e68505586284"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_arm64.tar.gz"
      sha256 "3c96807e0bc919543eab8f461d01ad55bb23c8e7d51424376ccb8e77462e67f7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_amd64.tar.gz"
      sha256 "bbc406065c9d1a6d5cc3466195d784342b799ae15543448df567284214c27d72"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_arm64.tar.gz"
      sha256 "f8c5df5517ad2be53ca2cd1a3a101233af2db6450fb2744925ebe81c75f08ebc"
    end
  end

  # No zap stanza required
end
