# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyjira" do
  name "lazyjira"
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyjira"

  on_macos do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_amd64.tar.gz"
      sha256 "781f58374ab15878ee99eca54df5a493e66fa434c2106f04c78003a2d0053bce"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_arm64.tar.gz"
      sha256 "9aaa5826ea070731417585e28834065d1b8280809a7994fa7e14a6edf0b36be3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_amd64.tar.gz"
      sha256 "d14befe61300812d83d71694a22476be78311b5680bd83c79238601c873fbebf"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_arm64.tar.gz"
      sha256 "d20a4bdb233b95b8040e5a6dfb1e5c367a7e47fa0db139388c57d4ac09f61f6b"
    end
  end

  # No zap stanza required
end
