# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.2.0/lazyjira_darwin_amd64.tar.gz"
      sha256 "a76fd99ba659175c4fcc868949a3d82d10a6ceb2e56f70744dd2fb8222f945f3"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.2.0/lazyjira_darwin_arm64.tar.gz"
      sha256 "e54a0814789a9f67b749f201f6178e24263b7f0b37298848a006a8c5258bab74"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.2.0/lazyjira_linux_amd64.tar.gz"
      sha256 "9b7435983276366399fb13bdb0e4a8d9d7eb7b68fded41aa77819f58dbbe71e6"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.2.0/lazyjira_linux_arm64.tar.gz"
      sha256 "0fd01a5e85783bf0b65470057c980d1d3f7e99ad77b158ddd5ffd1d6802c02dd"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  test do
    assert_match "lazyjira", shell_output("#{bin}/lazyjira --version")
  end
end
