# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/textfuel/lazyjira/releases/download/v1.1.0/lazyjira_darwin_amd64.tar.gz"
      sha256 "0df10c67763e79b86abef3bf640592feceb9548c7f8cb211a8665b7871ca3b20"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/textfuel/lazyjira/releases/download/v1.1.0/lazyjira_darwin_arm64.tar.gz"
      sha256 "df3c28bddcce4ebb5919155682f7bf74f1522b14edf4b394e8003f587b64dfb8"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v1.1.0/lazyjira_linux_amd64.tar.gz"
      sha256 "8e9dde0dad69ef87afa3b89898d52dc7bf5fff225cf688dbd83499f9b76cfb59"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v1.1.0/lazyjira_linux_arm64.tar.gz"
      sha256 "e094be22b7fdc81de4ca4674d521348c1b4c3e70cc7c2534ea2438871e18860f"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  test do
    assert_match "lazyjira", shell_output("#{bin}/lazyjira --version")
  end
end
